r"""Fixtures for pytest."""

# standard imports
# 3rd-party imports
import glob
import os
import sys
from pathlib import Path

import pytest
from PyQt5.QtCore import QSettings

from quicknxs.interfaces.configuration import Configuration
from quicknxs.interfaces.data_handling.filepath import RunNumbers
from quicknxs.interfaces.data_handling.instrument import Instrument
from quicknxs.interfaces.data_manager import DataManager
from quicknxs.interfaces.main_window import MainWindow
from test.ui import ui_utilities

pytest_plugins = ["mantid.fixtures"]

this_module_path = sys.modules[__name__].__file__


################################################
# FIXTURES AUTOMATICALLY APPLIED TO EVERY TEST #
################################################


@pytest.fixture(autouse=True)
def qsettings_tmp_path(tmp_path):
    """
    Set the location of the config file generated by QSettings to a temporary directory.

    This avoids:
    - unit tests affecting the local user settings in ~/.config/.quicknxs.conf and vice versa
    - settings spilling over between tests by having a unique settings file location in each test
      (thanks to `tmp_path` creating a unique directory for each test)
    """
    QSettings.setPath(QSettings.NativeFormat, QSettings.UserScope, str(tmp_path))


##################################
# FIXTURES THAT CAN BE REQUESTED #
##################################


@pytest.fixture(scope="session")
def DATA_DIR():
    return Path(__file__).parent / "data"


Instrument.file_search_template = str(Path(__file__).parent / "data" / "quicknxs-data" / "REF_M_%s")


@pytest.fixture(scope="module")
def data_server(DATA_DIR):
    r"""Object containing info and functionality for data files."""

    class _DataServe(object):
        _directory = str(DATA_DIR)
        _h5_path = "quicknxs-data"

        @property
        def directory(self):
            r"""Directory where to find the data es."""
            return self._directory

        @property
        def h5_path(self):
            r"""Directory where to find h5 data files."""
            return self._h5_path

        @property
        def h5_full_path(self):
            r"""Full path to directory where to find h5 data files."""
            return os.path.join(self.directory, self.h5_path)

        def path_to(self, basename):
            r"""Absolute path to a data file. If it doesn't exist, try to find it in the remote repository."""
            # looking in test/data
            file_path = os.path.join(self._directory, basename)
            if os.path.isfile(file_path):
                return file_path
            # looking in test/data/quicknxs-data
            file_path = os.path.join(self.directory, self.h5_path)
            file_path = os.path.join(file_path, basename)

            for ext in [".nxs.h5", "", "_event.nxs"]:
                if os.path.isfile(file_path + ext):
                    return file_path + ext
            raise IOError(f"File {basename} not found in data directory {self._directory}")

        def get_file_paths(self, number):
            instrument = Instrument()

            run_numbers = RunNumbers(number)

            file_list = list()

            for run_number in run_numbers.numbers:
                search_string = instrument.file_search_template % run_number
                matches = glob.glob(search_string + ".nxs.h5")  # type: Optional[List[str]]
                if not matches:  # Look for old-style nexus file name
                    search_string = instrument.legacy_search_template % run_number
                    matches = glob.glob(search_string + "_event.nxs")
                if len(matches) >= 1:
                    file_list.append(matches[0])  # there should be only one match, since we query with one run number

            return file_list

    return _DataServe()


@pytest.fixture
def main_window_with_data_factory(qtbot):
    """Test fixture that returns a main window with data loaded into it.

    Create as a factory to be able to do setup e.g. mock functions before instantiating the main window.
    """

    def _create():
        Configuration.setup_default_values()
        main_window = MainWindow()
        qtbot.addWidget(main_window)

        # load file list
        ui_utilities.setText(main_window.numberSearchEntry, str(42100), press_enter=True)

        # add two direct beams
        ui_utilities.set_current_file_by_run_number(main_window, 42100)
        main_window.actionAddDirectBeam.triggered.emit()
        ui_utilities.set_current_file_by_run_number(main_window, 42099)
        main_window.actionAddDirectBeam.triggered.emit()

        # add two data runs
        ui_utilities.set_current_file_by_run_number(main_window, 42112)
        main_window.actionAddRefl.triggered.emit()
        ui_utilities.set_current_file_by_run_number(main_window, 42113)
        main_window.actionAddRefl.triggered.emit()

        # set the first data run as the active run in the UI
        main_window.reduction_cell_activated(0, 0)

        return main_window

    return _create


@pytest.fixture
def data_manager_with_data_factory(data_server):
    """Test fixture that returns a data manager with data loaded into it.

    Create as a factory to be able to do setup e.g. mock functions before instantiating the data manager.
    """

    def _create():
        Configuration.setup_default_values()

        manager = DataManager(data_server.directory)

        # Add direct beams
        manager.load(data_server.path_to("REF_M_42099"), Configuration())
        manager.add_active_to_direct_beam_list()
        manager.load(data_server.path_to("REF_M_42100"), Configuration())
        manager.add_active_to_direct_beam_list()

        # Add reflected runs, direct beams should be automatically matched
        conf1 = Configuration()
        conf1.match_direct_beam = True
        manager.load(data_server.path_to("REF_M_42112"), conf1)
        manager.add_active_to_reduction()
        assert manager.get_active_direct_beam().number == "42099"
        conf2 = Configuration()
        conf2.match_direct_beam = True
        manager.load(data_server.path_to("REF_M_42113"), conf2)
        manager.add_active_to_reduction()
        assert manager.get_active_direct_beam().number == "42100"

        return manager

    return _create
