name: quicknxs
channels:
    - mantid/label/nightly
    - conda-forge
    - default
dependencies:
- mantidworkbench>=6.7.20230803,<6.8
- anaconda-client
- boa
- build
- codecov
- conda-build
- conda-verify
- pre-commit
- pylint
- pytest
- pytest-qt
- pytest-cov
- pytest-mock
- pytest-xvfb
- toml
- pip
- pip:
    - versioningit
    - check-wheel-contents
