name: quicknxs
channels:
    - mantid/label/main
    - conda-forge
    - default
dependencies:
- mantidworkbench=6.8
- anaconda-client
- boa
- build
- codecov
- conda-build
- conda-verify
- pre-commit
- pylint
- pytest
- pytest-qt
- pytest-cov
- pytest-mock
- pytest-xvfb
- sphinx
- sphinx_rtd_theme
- toml
- pip
- pip:
    - versioningit
    - check-wheel-contents
