name: quicknxs
channels:
    - mantid/label/main
    - conda-forge
    - default
dependencies:
- mantidworkbench=6.10.0
- anaconda-client
- boa
- codecov
- conda-build
- conda-verify
- libarchive
- libmamba
- pre-commit
- pylint
- pytest
- pytest-qt
- pytest-cov
- pytest-mock
- pytest-xvfb
- python-build
- sphinx
- sphinx_rtd_theme
- toml
- versioningit
- pip
- pip:
    - check-wheel-contents
