name: quicknxs
channels:
    - mantid/label/main
    - conda-forge
    - neutrons
    - default
dependencies:
- mantidworkbench>=6.6,<6.7
- boa
- build
- codecov
- conda-build
- conda-verify
- pylint
- pytest
- pytest-qt
- pytest-cov
- pytest-xvfb
- toml
- pip
- pip:
    - versioningit
    - check-wheel-contents
