[build-system]
requires = ["setuptools >= 47", "wheel", "toml", "versioningit"]
build-backend = "setuptools.build_meta"

[tool.versioningit.vcs]
method = "git"
default-tag = "4.0.1"

[tool.versioningit.next-version]
method = "minor"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}"
dirty = "{version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+d{build_date:%Y%m%d%H%M}"

[tool.versioningit.write]
file = "quicknxs/_version.py"

[tool.pytest.ini_options]
testpaths = ["test/"]

markers = ["datarepo: mark a test as using reflection_ui-data repository"]
