"""Fixtures for pytest."""

import glob
import logging
import os
import sys
from pathlib import Path

import numpy as np
import pytest
from PyQt5.QtCore import QSettings
from qtpy import QtWidgets

from quicknxs.models.configuration import Configuration
from quicknxs.models.data_set import CrossSectionData, NexusData
from quicknxs.models.instrument import Instrument
from quicknxs.presenters.data_handler import DataHandler
from quicknxs.utils.filepath import RunNumbers
from quicknxs.views.main_window import MainWindow
from tests.ui import ui_utilities

pytest_plugins = ["mantid.fixtures"]

this_module_path = sys.modules[__name__].__file__


def pytest_configure(config):
    """Suppress debug logging from pyvirtualdisplay.

    pytest-xvfb tears down the virtual display after pytest has already closed
    its log-capture streams.  pyvirtualdisplay emits several log.debug() calls
    during that teardown, which hit the closed stream and print harmless but
    noisy '--- Logging error ---' tracebacks to stderr.  Raising the logger
    level to WARNING filters those messages before they ever reach a handler.
    """
    logging.getLogger("pyvirtualdisplay").setLevel(logging.WARNING)


################################################
# FIXTURES AUTOMATICALLY APPLIED TO EVERY TEST #
################################################


@pytest.fixture(autouse=True)
def qsettings_tmp_path(tmp_path):
    """
    Set the location of the config file generated by QSettings to a temporary directory.

    This avoids:
    - unit tests affecting the local user settings in ~/.config/.quicknxs.conf and vice versa
    - settings spilling over between tests by having a unique settings file location in each test
      (thanks to `tmp_path` creating a unique directory for each test)
    """
    QSettings.setPath(QSettings.NativeFormat, QSettings.UserScope, str(tmp_path))


##################################
# FIXTURES THAT CAN BE REQUESTED #
##################################


@pytest.fixture(scope="session")
def DATA_DIR():
    return Path(__file__).parent / "data"


Instrument.file_search_template = str(Path(__file__).parent / "data" / "quicknxs-data" / "REF_M_%s")


@pytest.fixture(scope="module")
def data_server(DATA_DIR):
    r"""Object containing info and functionality for data files."""

    class _DataServer:
        _directory = str(DATA_DIR)
        _h5_path = "quicknxs-data"

        @property
        def directory(self):
            r"""Directory where to find the data es."""
            return self._directory

        @property
        def h5_path(self):
            r"""Directory where to find h5 data files."""
            return self._h5_path

        @property
        def h5_full_path(self):
            r"""Full path to directory where to find h5 data files."""
            return os.path.join(self.directory, self.h5_path)

        def path_to(self, basename):
            r"""Absolute path to a data file. If it doesn't exist, try to find it in the remote repository."""
            # looking in tests/data
            file_path = os.path.join(self._directory, basename)
            if os.path.isfile(file_path):
                return file_path
            # looking in tests/data/quicknxs-data
            file_path = os.path.join(self.directory, self.h5_path)
            file_path = os.path.join(file_path, basename)

            for ext in [".nxs.h5", "", "_event.nxs"]:
                if os.path.isfile(file_path + ext):
                    return file_path + ext
            raise OSError(f"File {basename} not found in data directory {self._directory}")

        def get_file_paths(self, number):
            instrument = Instrument()

            run_numbers = RunNumbers(number)

            file_list = list()

            for run_number in run_numbers.numbers:
                search_string = instrument.file_search_template % run_number
                matches = glob.glob(search_string + ".nxs.h5")  # type: list[str] | None
                if not matches:  # Look for old-style nexus file name
                    search_string = instrument.legacy_search_template % run_number
                    matches = glob.glob(search_string + "_event.nxs")
                if len(matches) >= 1:
                    file_list.append(matches[0])  # there should be only one match, since we query with one run number

            return file_list

    return _DataServer()


@pytest.fixture
def main_window_with_data_factory(qtbot):
    """Test fixture that returns a main window with data loaded into it.

    Create as a factory to be able to do setup e.g. mock functions before instantiating the main window.
    """

    def _create():
        Configuration.setup_default_values()
        main_window = MainWindow()
        qtbot.addWidget(main_window)

        # load file list
        ui_utilities.setText(main_window.numberSearchEntry, str(42100), press_enter=True)

        # add two direct beams
        ui_utilities.set_current_file_by_run_number(main_window, 42100)
        main_window.actionAddDirectBeam.triggered.emit()
        ui_utilities.set_current_file_by_run_number(main_window, 42099)
        main_window.actionAddDirectBeam.triggered.emit()

        # add two data runs
        ui_utilities.set_current_file_by_run_number(main_window, 42112)
        main_window.actionAddRefl.triggered.emit()
        ui_utilities.set_current_file_by_run_number(main_window, 42113)
        main_window.actionAddRefl.triggered.emit()

        # set the first data run as the active run in the UI
        main_window.set_active_reduction_data(True, 0)

        return main_window

    return _create


@pytest.fixture
def data_handler_with_data_factory(data_server):
    """Test fixture that returns a data manager with data loaded into it.

    Create as a factory to be able to do setup e.g. mock functions before instantiating the data manager.
    """

    def _create():
        Configuration.setup_default_values()

        manager = DataHandler(data_server.directory)

        # Add direct beams
        manager.load(data_server.path_to("REF_M_42099"), Configuration())
        manager.add_active_to_direct_beam_list()
        manager.load(data_server.path_to("REF_M_42100"), Configuration())
        manager.add_active_to_direct_beam_list()

        # Add reflected runs, direct beams should be automatically matched
        conf1 = Configuration()
        conf1.match_direct_beam = True
        manager.load(data_server.path_to("REF_M_42112"), conf1)
        manager.add_active_to_reduction()
        assert manager.get_active_direct_beam().run_number == "42099"
        conf2 = Configuration()
        conf2.match_direct_beam = True
        manager.load(data_server.path_to("REF_M_42113"), conf2)
        manager.add_active_to_reduction()
        assert manager.get_active_direct_beam().run_number == "42100"

        return manager

    return _create


@pytest.fixture
def main_window_with_mock_runs(qtbot, mocker, tmp_path):
    """MainWindow with two mock reflected runs and two mock direct beam runs.

    Injects NexusData objects directly into the DataHandler (no Nexus file content is read),
    and pre-populates the file list widget with their file names.

    Empty placeholder files are created in tmp_path so that open_file()'s existence check
    passes when the file list selection signal triggers file_open_from_list().
    DataHandler.load() finds each NexusData by its full path in direct_beam_list /
    reduction_list, so no actual Nexus data is ever parsed.

    Both MainWindow.file_loaded and MainHandler.file_loaded are patched out so that
    the plotting machinery is not triggered. set_active_reduction_data still calls
    active_data_changed() explicitly after file_loaded returns.
    """
    config = Configuration()
    xs = CrossSectionData("Off_Off", config)
    xs.tof_edges = np.array([0.1, 0.2, 0.3, 0.4])

    names = ["REF_M_40785.nxs.h5", "REF_M_40782.nxs.h5", "REF_M_40786.nxs.h5", "REF_M_40787.nxs.h5"]
    for name in names:
        (tmp_path / name).touch()
    # add summed file to file list
    names.append("REF_M_40782.nxs.h5+REF_M_40785.nxs.h5")

    run_a = NexusData(str(tmp_path / "REF_M_40785.nxs.h5"), config)
    run_a.cross_sections["Off_Off"] = xs
    run_a.run_number = "40785"

    # run created with Open & Sum Multiple Files
    run_b = NexusData(str(tmp_path / "REF_M_40782.nxs.h5") + "+" + str(tmp_path / "REF_M_40785.nxs.h5"), config)
    run_b.cross_sections["Off_Off"] = xs
    run_b.run_number = "40782"

    run_c = NexusData(str(tmp_path / "REF_M_40782.nxs.h5"), config)
    run_c.cross_sections["Off_Off"] = xs
    run_c.run_number = "40782"

    run_db = NexusData(str(tmp_path / "REF_M_40786.nxs.h5"), config)
    run_db.cross_sections["Off_Off"] = xs
    run_db.run_number = "40786"

    run_db2 = NexusData(str(tmp_path / "REF_M_40787.nxs.h5"), config)
    run_db2.cross_sections["Off_Off"] = xs
    run_db2.run_number = "40787"

    main_window = MainWindow()
    qtbot.addWidget(main_window)
    handler = main_window.file_handler

    dm = main_window.data_handler
    dm.current_directory = str(tmp_path)
    dm.peak_reduction_lists[dm.active_reduction_list_index] = [run_a, run_b, run_c]
    dm.direct_beam_list = [run_db, run_db2]
    # Set an initial active run so that initialize_additional_reduction_table can read
    # active_cross_section.name if addDataTable() is called during a test.
    dm._nexus_data = run_a
    dm.active_cross_section = xs

    for name in names:
        QtWidgets.QListWidgetItem(name, main_window.ui.file_list)

    # Bypass the plotting machinery triggered by both call paths into file_loaded:
    # - MainWindow.file_loaded() is called by set_active_reduction_data / set_active_direct_beam
    # - MainHandler.file_loaded() is called directly by open_file (via file_open_from_list)
    # Retain only the call to active_data_changed to ensure the radio button state is updated.
    # MainWindow.file_loaded -> MainHandler.file_loaded -> active_data_changed in production;
    # both are patched here to skip plotting but preserve the active_data_changed side effect.
    mocker.patch.object(main_window, "file_loaded", side_effect=handler.active_data_changed)
    mocker.patch.object(handler, "file_loaded", side_effect=handler.active_data_changed)

    # Populate the reduction table with the mock runs
    xs_name = dm.active_cross_section.name
    handler.reduction_table.setRowCount(len(dm.reduction_list))
    for i, run in enumerate(dm.reduction_list):
        handler.update_reduction_table(handler.reduction_table, i, run.cross_sections[xs_name])

    # Populate the direct beam table with the mock runs
    handler.direct_beam_table.setRowCount(len(dm.direct_beam_list))
    for i, run in enumerate(dm.direct_beam_list):
        handler.update_direct_beam_table(i, run.cross_sections[xs_name])

    return main_window
