import os

from qtpy.QtCore import QObject, QUrl, Qt, Signal
from qtpy.QtQuickWidgets import QQuickWidget
from qtpy.QtWidgets import QDialog, QVBoxLayout, QWidget

from quicknxs.interfaces.configuration import Configuration
from quicknxs.interfaces.event_handlers.widgets import AcceptRejectDialog


class _CheckBoxProxy:
    """Proxy for a QML CheckBox item that mimics the QCheckBox interface."""

    def __init__(self, qml_item: QObject):
        self._item = qml_item

    def isChecked(self) -> bool:
        return bool(self._item.property("checked"))

    def setChecked(self, value: bool) -> None:
        self._item.setProperty("checked", value)


class _DoubleSpinBoxProxy:
    """Proxy for a QML SpinBox item that mimics the QDoubleSpinBox interface.

    Parameters
    ----------
    qml_item:
        The QML SpinBox QObject.
    scale_factor:
        Factor used to convert between the integer QML SpinBox value and the
        floating-point Python value (Python value = QML value / scale_factor).
    """

    def __init__(self, qml_item: QObject, scale_factor: float = 1.0):
        self._item = qml_item
        self._scale = scale_factor

    def value(self) -> float:
        return self._item.property("value") / self._scale

    def setValue(self, val: float) -> None:
        self._item.setProperty("value", round(val * self._scale))


class _DeadTimeUI:
    """Container of proxy widgets that mimics the interface generated by loadUi."""

    def __init__(self, qml_root: QObject):
        use_paralyzable_item = qml_root.findChild(QObject, "use_paralyzable")
        dead_time_value_item = qml_root.findChild(QObject, "dead_time_value")
        dead_time_tof_item = qml_root.findChild(QObject, "dead_time_tof")

        self.use_paralyzable = _CheckBoxProxy(use_paralyzable_item)
        # dead_time_value uses a scale factor of 10 so that the QML integer
        # SpinBox (which stores e.g. 42) maps to the Python float 4.2.
        self.dead_time_value = _DoubleSpinBoxProxy(dead_time_value_item, scale_factor=10.0)
        self.dead_time_tof = _DoubleSpinBoxProxy(dead_time_tof_item, scale_factor=1.0)


class DeadTimeSettingsView(QDialog):
    """Dialog to choose the dead time correction options."""

    reload_files_signal = Signal()

    def __init__(self, parent: QWidget):
        super().__init__(parent)
        self.setWindowTitle("Dead Time Settings")
        self.setModal(True)
        self.setMaximumSize(439, 150)

        qml_path = os.path.join(os.path.dirname(__file__), "deadtime_settings.qml")
        self._quick_widget = QQuickWidget(self)
        self._quick_widget.setResizeMode(QQuickWidget.SizeRootObjectToView)
        self._quick_widget.setSource(QUrl.fromLocalFile(qml_path))

        qml_root = self._quick_widget.rootObject()
        qml_root.accepted.connect(self.accept)
        qml_root.rejected.connect(self.reject)

        self.ui = _DeadTimeUI(qml_root)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self._quick_widget)
        self.resize(428, 150)

        self.set_state_from_global_config()

    def keyPressEvent(self, event):
        """Accept the dialog on Enter/Return and reject it on Escape."""
        if event.key() in (Qt.Key_Enter, Qt.Key_Return):
            self.accept()
        elif event.key() == Qt.Key_Escape:
            self.reject()
        else:
            super().keyPressEvent(event)

    def set_state_from_global_config(self):
        """Populate the form with the current global configuration."""
        self.ui.use_paralyzable.setChecked(Configuration.paralyzable_deadtime)
        self.ui.dead_time_value.setValue(Configuration.deadtime_value)
        self.ui.dead_time_tof.setValue(Configuration.deadtime_tof_step)

    def check_values_changed(self):
        """
        Check if the dialog settings entries have been changed by the user.

        Returns
        -------
        bool: - True if dialog values are different from the global configuration
              - False if dialog values are the same as the global configuration
        """
        if not self.ui.use_paralyzable.isChecked() == Configuration.paralyzable_deadtime:
            return True
        if not self.ui.dead_time_value.value() == Configuration.deadtime_value:
            return True
        if not self.ui.dead_time_tof.value() == Configuration.deadtime_tof_step:
            return True
        return False

    def ask_user_ok_to_reload_files(self):
        """Shows dialog asking user to confirm reloading all files."""
        message = "Change dead-time settings and reload all files?"
        dialog = AcceptRejectDialog(self, title="Reload files", message=message)
        proceed = dialog.exec_()
        return proceed

    def accept(self):
        """Read in the options on the form when the OK button is clicked and update the global configuration."""
        if self.check_values_changed() and self.ask_user_ok_to_reload_files():
            Configuration.paralyzable_deadtime = self.ui.use_paralyzable.isChecked()
            Configuration.deadtime_value = self.ui.dead_time_value.value()
            Configuration.deadtime_tof_step = self.ui.dead_time_tof.value()
            # trigger reloading all files to apply the new dead-time settings
            self.reload_files_signal.emit()
        self.close()
