# load information from setup.cfg/setup.py
# load information from pyproject.toml
{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}
{% set license = project.get('license').get('text') %}
{% set description = project.get('description') %}
{% set project_url = pyproject.get('project', {}).get('urls') %}
{% set url = project_url.get('homepage') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = version.split('+')[0] %}
# change the build number by hand if you want to rebuild the package
{% set build_number = 0 %}

package:
  name: "quicknxs"
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  build: {{ build_number }}
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - versioningit

  build:
    - mantid
    - matplotlib
    - setuptools
    - qtpy
    - versioningit

  run:
    - mantid=6.10.0
    - matplotlib
    - qtpy
    - qt>=5.12,<6

test:
  imports:
    - quicknxs

about:
  home: {{ url }}
  license: {{ license }}
  license_family: APACHE
  license_file: ../LICENSE
  summary: {{ description }}

extra:
  recipe-maintainers:
    - Mathieu Doucet
    - Pete Peterson
